const router = require('express').Router();const loginall = require('./page/loginall');const imgupload = require('./page/imgupload');const insertall = require('./page/insertall');const viewall = require('./page/viewall');const searchall = require('./page/searchall');const searchallpg = require('./page/searchallpg');const updateall = require('./page/updateall');

// Login User
router.post('/Register',loginall.Register);//imgupload
router.post('/addimgpropertyall',imgupload.addimgpropertyall);router.post('/addimgpropertyallpg',imgupload.addimgpropertyallpg);router.post('/editimgpropertyall',imgupload.editimgpropertyall);//insertall
router.post('/addpropertyallsss',insertall.addpropertyallsss);router.post('/addpropertyallpgsss',insertall.addpropertyallpgsss);router.post('/deletevideolistsss',insertall.deletevideolistsss);router.post('/deletevideolistpgsss',insertall.deletevideolistpgsss);//updateallrouter.post('/editpropertyallsss',updateall.editpropertyallsss);router.post('/editpropertyallpgsss',updateall.editpropertyallpgsss);router.post('/savesallsss',updateall.savesallsss);router.post('/savesallpgsss',updateall.savesallpgsss);//viewall
router.get('/Rentsallsss/:pageNumber',viewall.Rentsallsss);router.post('/allimgssslist',viewall.allimgssslist);router.post('/viewallsssallsss',viewall.viewallsssallsss);router.get('/buysallsss/:pageNumber',viewall.buysallsss);router.get('/homebuyallsss',viewall.homebuyallsss);router.get('/homerentallsss',viewall.homerentallsss);router.post('/userlistallsss',viewall.userlistallsss);router.get('/buysalladminsss/:pageNumber/:pageId',viewall.buysalladminsss);router.get('/Pgallsss/:pageNumber',viewall.Pgallsss);router.post('/allimgssspglist',viewall.allimgssspglist);router.post('/allcategoriesssaaa',viewall.allcategoriesssaaa);router.post('/viewallsssallpgsss',viewall.viewallsssallpgsss);router.get('/pgalladminsss/:pageNumber/:pageId',viewall.pgalladminsss);router.post('/imgorderallsss',viewall.imgorderallsss);router.post('/imgorderallpgsss',viewall.imgorderallpgsss);//searchall
router.get('/seachlistallsss/:pageNumber/:type/:locations/:property/:budgetMin/:budgetMax',searchall.seachlistallsss);//seachlistallpg
router.get('/seachlistallpgsss/:pageNumber/:type/:locations/:pgboys/:pggirls/:budgetMin/:budgetMax',searchallpg.seachlistallpgsss);// https://www.youtube.com/watch?v=1PBcSzTbbjw
module.exports = router;